package main

import (
	"log"

	"github.com/ahmadeko2017/backed-golang-tugas-1/internal/handler"
	"github.com/ahmadeko2017/backed-golang-tugas-1/internal/middleware"
	"github.com/ahmadeko2017/backed-golang-tugas-1/internal/repository"
	"github.com/ahmadeko2017/backed-golang-tugas-1/internal/service"
	"github.com/ahmadeko2017/backed-golang-tugas-1/pkg/database"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/ahmadeko2017/backed-golang-tugas-1/docs" // This will be generated by swag init
)

// @title           Category API
// @version         1.0
// @description     This is a sample server for managing categories.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /

func main() {
	// Connect to DB
	database.Connect()

	// Setup Repository
	categoryRepo := repository.NewCategoryRepository(database.DB)

	// Setup Service
	categoryService := service.NewCategoryService(categoryRepo)

	// Setup Handler
	categoryHandler := handler.NewCategoryHandler(categoryService)

	// Setup Router
	r := gin.Default()

	// Add Rate Limit Middleware (e.g., 10 rps)
	r.Use(middleware.RateLimitMiddleware(10))

	// Routes
	c := r.Group("/categories")
	{
		c.GET("", categoryHandler.GetAllCategories)
		c.POST("", categoryHandler.CreateCategory)
		c.GET("/:id", categoryHandler.GetCategoryByID)
		c.PUT("/:id", categoryHandler.UpdateCategory)
		c.DELETE("/:id", categoryHandler.DeleteCategory)
	}

	// Swagger
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start server
	log.Println("Server running on port 8080")
	if err := r.Run(":8080"); err != nil {
		log.Fatal("Failed to start server: ", err)
	}
}
